<template>
    <div class="container">
        <div class="text-container">
            <h4 class="text-center mdc-typography--headline4">Kunsthistorische Analyse des Buchschmucks im Magnum Legendarium Austriacum<a href="#_ftn1" name="_ftnref1">[1]</a></h4>
            <h6 class="text-center mdc-typography--subtitle1">Susanne Rischpler</h6>
            <div class="description mdc-typography--body2">
                <p>In der vorliegenden kunsthistorischen Untersuchung wurden alle 21 erhaltenen Handschriften des Magnum Legendarium Austriacum, auch jene mit bescheidenerem Buchschmuck, stilkritisch analysiert.<a href="#_ftn2" name="_ftnref2">[2]</a> Die methodische &nbsp;Vorgehensweise der Analyse orientiert sich dabei an den Katalogen der &bdquo;Mitteleurop&auml;ischen Schulen&ldquo; zur Erschlie&szlig;ung der illuminierten Handschriften und Inkunabeln der &Ouml;sterreichischen Nationalbibliothek, Wien. F&uuml;r die Ausstattung jedes einzelnen Bandes wurde eine Beschreibung angelegt, die jeweils einen hierarchisch aufgebauten &Uuml;berblick &uuml;ber den Buchschmuck liefert und in den jeweiligen Beschreibungen der Handschriften auf der Webdatenbank manuscripta.at zur Verf&uuml;gung gestellt wird. Demnach stellt folgende Text eine zusammenfassende Sichtweise dar, die anhand der Stilanalysen bei den jeweiligen Handschriften und mittels der Volldigitalisate nachvollzogen werden kann.</p>
    <p>Vorausgeschickt wird eine tabellarische &Uuml;bersicht &uuml;ber die chronologische Reihenfolge der Entstehung der B&auml;nde, die sich einerseits aus der im Rahmen des VISCOM-Projekts erstellten Studie Diarmuid &Oacute; Riains und der hier ausgef&uuml;hrten kunsthistorischen Analyse ergeben:</p>
    <p>&nbsp;</p>
    <div style="padding-left: 50px;">
    <p>Admont, Cod. 25 und 24, zwischen 1170 und 1180/85</p>
    <p>Heiligenkreuz, Cod. 11&ndash;15, 1183/um 1200</p>
    <p>Wien, &Ouml;NB, Cod. 336, St. P&ouml;lten, Anfang 13. Jahrhundert</p>
    <p>Zwettl, Cod. 13, 24, 14 und 15, 1. Viertel oder 1. Drittel 13. Jahrhundert</p>
    <p>Lilienfeld, Cod. 58&ndash;60, 1. Drittel 13. Jahrhundert (nach 1202/1206)</p>
    <p>Melk, Cod. 388, 4. oder 5. Jahrzehnt 13. Jahrhundert (nach 1230)</p>
    <p>Melk, Cod. 546, 3. Viertel 15. Jahrhundert</p>
    <p>Melk, Cod. 97, 3. Viertel 15. Jahrhundert (vor 1471)</p>
    <p>Melk, Cod. 492, vor 1471 (wohl 1460er Jahre)</p>
    <p>Melk, Cod. 101, 3. Viertel 15. Jahrhundert (vor 1471)</p>
    <p>Melk, Cod. 16, dat. 1471, Buchschmuck wohl etwas sp&auml;ter</p>
    <p>Melk, Cod. 100, nach 1471 mit Tendenz zum Jahrzehntende</p>
    </div>
    <p><strong>&nbsp;</strong></p>
    <p><strong>Die Technik des Buchschmucks im MLA</strong></p>
    <p>Bei jenen B&auml;nden des Magnum Legendarium Austriacum, deren Entstehungszeitraum sich insgesamt vom letzten Viertel des 12. bis in die erste H&auml;lfte des 13. Jahrhunderts erstreckt, ist die Federzeichnung die dominierende Technik. Vor der Jahrhundertwende wird sie in den Skriptorien des Zisterzienserordens &ndash; diesem geh&ouml;ren Heiligenkreuz, Zwettl und Lilienfeld an &ndash; propagiert, dessen Statuten Schmuckf&uuml;lle im Klosterbereich zu vermeiden trachteten.<a href="#_ftn3" name="_ftnref3">[3]</a> Zudem beweist die rheinl&auml;ndisch beeinflusste Regensburger Buchmalerei, die auf die Ausstattung des Heiligenkreuzer Legendars wirkte, eine Vorliebe f&uuml;r die Federzeichnung, welche oftmals zweifarbig in roter und brauner Tinte ausgef&uuml;hrt wird.<a href="#_ftn4" name="_ftnref4">[4]</a> Was sich bei den vergleichsweise bescheidenen Rankeninitialen und fig&uuml;rlichen Initialen der Admonter B&auml;nde abzeichnet, dass n&auml;mlich die rote Federzeichnung dominiert, braune oder schwarze Tinte den Details vorbehalten bleibt und Kolorierung angewendet wird, setzt sich im Heiligenkreuzer Legendar in st&auml;rkerem Ausma&szlig; fort. Lediglich eine von f&uuml;nf H&auml;nden zeichnet in Schwarz, die anderen H&auml;nde verwenden &ndash; wie auch im Zwettler Legendar &ndash; vorrangig rote Tinte. Die Kolorierung spielt im Heiligenkreuzer Legendar zwar noch nicht die Rolle wie im Zwettler MLA, doch wird der Einsatz der Farbe in den Heiligenkreuzer B&auml;nden so wichtig, dass man von einer Neuerung sprechen kann: Nicht nur Binnen‑ und Au&szlig;engr&uuml;nde, sondern auch Rankenverl&auml;ufe und Figurenpartien werden mit Farben, die man mit dem Pinsel auftr&auml;gt, ausgemalt beziehungsweise modelliert. Zur Charakterisierung der einzelnen Buchmaler(teams) tragen sowohl in den Heiligenkreuzer als auch in den Zwettler B&auml;nden die ihnen eigenen Farbpaletten und ‑kombinationen bei, wobei die erste Hand des Zwettler Legendars auch Gold zum Einsatz bringt und nicht nur Binnen‑ und Au&szlig;engr&uuml;nden, sondern auch Figuren und Rankenwerk koloriert (und modelliert). Im Melker Cod. 388 aus der ersten H&auml;lfte des 13. Jahrhunderts sind die Rankeninitialen in Rot und die fig&uuml;rlichen Initialen &uuml;berwiegend in Schwarz gezeichnet und die Initialgr&uuml;nde koloriert. Bei den restlichen Melker B&auml;nden, die im dritten Viertel des 15. Jahrhunderts entstanden, wurden die Ornamentalinitialen mit Deckfarbe im Farbdreiklang Gr&uuml;n, Blau und Rosa koloriert. In den sorgf&auml;ltiger ausgestatteten Melker Codices 101 und 100 fand auch Gold Anwendung.</p>
    <p>&nbsp;</p>
    <p><strong>Admont &ndash; eigenkl&ouml;sterliche Hauskopie?</strong></p>
    <p>F&uuml;r die beiden &auml;ltesten erhaltenen B&auml;nde des MLA-Corpus &ndash; Admont, Cod. 25 und 24 &ndash; stand bislang eine detaillierte Buchschmuck-Analyse aus, die gegebenenfalls datierungs‑ und/oder lokalisierungsrelevante Ergebnisse h&auml;tte liefern k&ouml;nnen.</p>
    <p>Rezente stemmatische Studien von Diarmuid &Oacute; Riain deuten auf das Benediktinerstift Admont nicht nur als Schreibort der einzigen direkt vom Ur-MLA angefertigten Kopie, sondern auch als Kompilationsort des MLA.<a href="#_ftn5" name="_ftnref5">[5]</a> Die Voraussetzungen daf&uuml;r &ndash; eine gut ausgestattete Bibliothek und ein leistungsf&auml;higes Skriptorium &ndash; waren in Admont vorhanden. Nimmt man die beiden Admonter B&auml;nde in der Tat als das &auml;lteste erhaltene MLA-Exemplar an, dann k&ouml;nnte es sich dabei um eine &bdquo;Hauskopie&ldquo; handeln, die im Admonter Skriptorium hergestellt wurde, bevor man das Ur-MLA an andere Kl&ouml;ster aush&auml;ndigte. &Oacute; Riain deutet die im MLA enthaltene Sammlung der Salzburger Bischofsviten sowie die Vita Mariani auf 1181 bzw. 1177/85 als termini post quos und 1200 als terminus ante quem f&uuml;r die Kompilation des Legendars hin.<a href="#_ftn6" name="_ftnref6">[6]</a> Auch wenn man den Kompilationsvorgang fr&uuml;h in diesem Zeitraum ansetzt, also im vorletzten Jahrzehnt des 12. Jahrhunderts, kann der Buchschmuck des Admonter Exemplars, das erst noch vom Ur-MLA abgeschrieben werden musste, fr&uuml;hestens um die Mitte oder in der zweiten H&auml;lfte der 1180er Jahre entstanden sein. Die Buchschmuckanalyse (vgl. Admont, <a href="http://manuscripta.at/?ID=26825" target="_blank">Cod. 25</a>, &bdquo;Stil und Einordnung&ldquo;) deutet jedoch darauf hin, dass die Ausstattung des Admonter MLA, die mit gro&szlig;er Wahrscheinlichkeit vor Ort in Admont geschaffen wurde, wohl nicht nach 1180 entstanden ist. Das hei&szlig;t, dass Kompilation und Kopieren bereits im drittletzten Jahrzehnt des 12. Jahrhunderts stattgefunden haben m&uuml;ssten.</p>
    <p>K&ouml;nnten demnach schon die Jahre 1168/69, als der &ouml;sterreichische Herzog Heinrich II. Jasomirgott (reg. 1144&ndash;1177) die Vogtei &uuml;ber das Kloster Admont erlangte, ein f&uuml;r die Kompilation des MLA entscheidender Zeitpunkt gewesen sein? Durch seinen Amtsantritt kam das Kloster unter den Einfluss der Babenberger. Heinrich erhielt das Vogtamt als Lehen 1168/69 von den Salzburger Erzbisch&ouml;fen, die mit Konrad II., ein Bruder des Herzogs, und Adalbert III., sein Neffe, der Familie der Babenberger angeh&ouml;rten.<a href="#_ftn7" name="_ftnref7">[7]</a> Geht man davon aus, dass in den Jahren 1168/69 beziehungsweise an der Wende zu den 1170er Jahren Planungen f&uuml;r MLA-Kompilation begannen und diese im Laufe der 1170er Jahre in Admont umgesetzt wurden, dann k&ouml;nnte die heute noch erhaltene Admonter Kopie schon gegen Ende 1170er Jahre, sp&auml;testens um 1180, vorgelegen haben.</p>
    <p>Stilistisch sind die beiden Legendarb&auml;nde zweifelsohne dem Admonter Skriptorium zuzuweisen, das Einfl&uuml;sse aus dem &ouml;sterreichisch-s&uuml;ddeutschen Raum verarbeitete, unter anderem aus der Salzburger Buchkunst der Zeit. Diese Tendenz ist nicht verwunderlich, da Admont 1074 als Eigenkloster des Salzburger Erzbischofs gegr&uuml;ndet und von der Erzabtei St. Peter aus besiedelt worden war; auch als sich in Admont ab etwa der Mitte des 12. Jahrhunderts ein florierender Skriptoriumsbetrieb etabliert hatte,<a href="#_ftn8" name="_ftnref8">[8]</a> verlor das Kloster nicht den Kontakt zu seinen Wurzeln. Der Machteinfluss, der vom Sitz des Erzbischofs auf das Eigenkloster ausging, d&uuml;rfte auch weiterhin einen Transfer im Buchwesen mitgetragen haben.</p>
    <p>&nbsp;</p>
    <p><strong>Heiligenkreuz &ndash; Gro&szlig;projekt und stilistischer Melting Pot I</strong></p>
    <p>F&uuml;r das Heiligenkreuzer MLA best&auml;tigen sich die bisherigen Erkenntnisse zu Lokalisierung und Datierung: Dieses Legendar wurde vor Ort in der vom Babenberger Markgrafen Leopold III. 1133 gestifteten Zisterze Heiligenkreuz gegen Ende des 12. Jahrhunderts geschaffen.<a href="#_ftn9" name="_ftnref9">[9]</a></p>
    <p>Auf Heiligenkreuz als Entstehungsort weisen die lokalen Schreiber und Buchmaler (vgl. die Auswertung auf <a href="http://www.scriptoria.at/cgi-bin/sc_mss.php" target="_blank">scriptoria.at</a>). F&uuml;r die Datierung ist die im letzten Band (Cod. 14) auf <a href="http://manuscripta.at/diglit/AT3500-14/0066?sid=90bda636da41760be652079f6684ee0f" target="_blank">f. 32vb</a> eingetragene Liste der <em>episcopi Salisburgensis ecclesie</em> besonders aussagekr&auml;ftig, die mit Erzbischof Adalbert III. schlie&szlig;t. Da Adalbert <a href="http://manuscripta.at/diglit/AT3500-14/0066?sid=90bda636da41760be652079f6684ee0f" target="_blank">f. 33ra</a> als aktueller W&uuml;rdentr&auml;ger angesprochen wird (<em>&hellip; usque ad presentem dominum A</em>[<em>dalbertum</em>]), ist anzunehmen, dass er zur Zeit des Schreibvorgangs noch lebte (s. Fingernagel 1985/2, 63f.). Das Legendar d&uuml;rfte in Heiligenkreuz somit im Zeitraum nach 1183 bis zur Jahrhundertwende fertig geschrieben gewesen sein.<a href="#_ftn10" name="_ftnref10">[10]</a> Damit verzahnt ist seine buchmalerische Gestaltung anzusetzen.</p>
    <p>Das aufw&auml;ndig und sorgf&auml;ltig geschm&uuml;ckte Heiligenkreuzer Exemplar eignet sich bestens, um Vorgehensweisen bei einem buchmalerischen Gro&szlig;projekt, wie es die Ausstattung einer mehrb&auml;ndigen Legendensammlung darstellt, aufzuzeigen. Seine &uuml;ber 1000 erhaltenen Bl&auml;tter wurden von f&uuml;nf H&auml;nden, hinter denen sich maximal zehn Einzelzeichner verbergen, mit insgesamt 45 fig&uuml;rlichen Initialen, weit &uuml;ber 500 Rankeninitialen und einer Vielzahl von dekorierten Initialmajuskeln verziert. Der f&uuml;r die Ausschm&uuml;ckung des Heiligenkreuzer MLA anzunehmende Zeitraum darf also getrost auf mehrere Jahre angesetzt werden.</p>
    <p>Die Schreiber reichten die von ihnen fertiggestellten Lagen nach und nach an die Buchmaler weiter. Dieser ineinandergreifende Prozess l&auml;sst sich im Heiligenkreuzer Legendar in gewissem Ma&szlig; transparent machen, besonders an der umfangreichen Gruppe der Rankeninitialen. Beispielsweise wurden die etwa 130 Rankeninitialen im dritten Band des Heiligenkreuzer Legendars von drei Illuminatorenh&auml;nden ausgef&uuml;hrt, die sich teilweise wiederum in Teams untergliedern lassen.</p>
    <a href="/assets/Heiligenkreuz-Maler.pdf" target="_blank"><img style="max-width: 100%; max-height: 600px;" src="/img/heiligenkreuz_maler.png"></a>
    <p><strong>&nbsp;</strong></p>
    <p><strong>Vermittlungswege der Buchkunst im Heiligenkreuzer MLA</strong></p>
    <p>Alle am Heiligenkreuzer Legendar beteiligten Zeichner beziehungsweise Buchmalerteams spiegeln stilistische Einfl&uuml;sse wider, die sich haupts&auml;chlich aus der niederrheinischen, das hei&szlig;t im K&ouml;lner Raum ausge&uuml;bten Buchmalerei des dritten Viertels des 12. Jahrhunderts zu speisen scheinen. Die niederrheinische Buchkunst wurde ihrerseits durch die maasl&auml;ndische gepr&auml;gt und &uuml;ber Regensburg, insbesondere durch das Benediktinerkloster Pr&uuml;fening, in den bayrisch-&ouml;sterreichischen Raum vermittelt.<a href="#_ftn11" name="_ftnref11">[11]</a> Diesen Einfluss hat die neuere Forschung wiederholt diskutiert;<a href="#_ftn12" name="_ftnref12">[12]</a> daher nur ein kurzer Blick auf ebenjenen plausiblen Vermittlungsweg, der auf einem engen, von West nach Ost f&uuml;hrenden Beziehungsstrang zwischen Klerikern, Kl&ouml;stern und deren Skriptorien beruht. Eine Schl&uuml;sselrolle kommt Kuno von Siegburg zu, der von 1126 bis 1132 das Amt des Bischofs von Regensburg bekleidete. Er war mit Rupert von Deutz freundschaftlich verbunden und f&ouml;rderte die Verbreitung seiner Werke.<a href="#_ftn13" name="_ftnref13">[13]</a> So wurde auch in Heiligenkreuz ein Text des Rupert (Apokalypsekommentar, <a href="http://manuscripta.at/?ID=30636" target="_blank">Cod. 83</a>) abgeschrieben und mit Illustrationen versehen, deren Figurenstil auf Regensburg-Pr&uuml;feninger Arbeiten der Zeit fu&szlig;t.</p>
    <p>Dar&uuml;ber hinaus war Bamberg eine Schaltstelle des Vorlagentransfers. Schon Otto von Bamberg, der das Kloster Pr&uuml;fening gr&uuml;ndete und von 1102 bis 1139 als Bischof von Bamberg wirkte, pflegte Beziehungen ins Rheinland, sp&auml;ter tat das auch Bischof Eberhard von Bamberg (1146&ndash;1170). In der Kanzlei des Bamberger Bischofs war in den 1150er Jahren und um 1162/63 der Pr&uuml;feninger Bibliothekar Wolfger t&auml;tig, der enge Kontakte zu bayrischen Nachbarkl&ouml;stern und nach Salzburg unterhielt. Es ist gut nachvollziehbar, dass sich in solchen Netzwerken neue Tendenzen in der Buchmalerei problemlos nach Bamberg und in den bayrisch-&ouml;sterreichischen Raum verbreiten konnten.</p>
    <p>Der Einfluss der rheinl&auml;ndisch inspirierten Regensburg-Pr&uuml;feninger Buchmalerei manifestiert sich in Heiligenkreuz nicht erstmalig mit dem Gro&szlig;projekt des Legendars, sondern war bereits ab dem dritten Viertel des 12. Jahrhunderts im dortigen Skriptorium wirksam geworden. Als wichtiger Faktor l&auml;sst er sich in einer recht umfangreichen Sancrucenses-Gruppe nachweisen, aus der die Augustinus-Handschrift <a href="http://manuscripta.at/?ID=30404" target="_blank">Cod. 24</a> in Bezug auf die stilistische Relevanz f&uuml;r das Legendar heraussticht.</p>
    <p>Bislang verkn&uuml;pfte man die Heiligenkreuzer Legendensammlung vor allem durch die in der zweiten H&auml;lfte des dritten Bandes nachweisbare Hand 4 mit der von niederrheinischen Werken angeregten Regensburg-Pr&uuml;feninger Buchmalerei.<a href="#_ftn14" name="_ftnref14">[14]</a> Dieser Einfluss kann auch f&uuml;r die erste Zeichnerhand nachgewiesen werden: bei der Gruppe der Rankeninitialen f&uuml;r die Gestaltung von Initialleisten und Rankenbl&auml;ttern, bei den fig&uuml;rlichen Initialen f&uuml;r anatomische und physiognomische Eigenheiten sowie f&uuml;r die Draperie.</p>
    <p>Die buchmalerischen Anst&ouml;&szlig;e entsprangen jedoch nicht nur dem maasl&auml;ndisch-niederrheinischen Gebiet, sondern auch dem nord‑ und ostfranz&ouml;sischen Raum, was beispielsweise die dritte Hand in der Motivik ihrer Rankeninitialen oder die f&uuml;nfte Hand durch die Gestaltung ihrer fig&uuml;rlichen Initialen belegt. Die zweite und wiederum die dritte Legendarhand, die Rankenwirbel und radial angeordnete Blattformationen mit fangarmartig ausgreifenden Blattgebilden einsetzen, welche von unkolorierten hunde‑ oder l&ouml;wenartigen Tierfig&uuml;rchen bev&ouml;lkert sind, deuten dar&uuml;ber hinaus auf mittelbare Einfl&uuml;sse des Channel Style. Dieser in der zweiten H&auml;lfte des 12. Jahrhunderts gebr&auml;uchliche Dekorstil mit den f&uuml;r ihn typischen Spiralranken und Oktopusbl&auml;ttern, die von kleinem wei&szlig;em Getier bev&ouml;lkert sind, wurde nach seinem Hauptverbreitungsgebiet diesseits und jenseits des Kanals in S&uuml;dengland und Nordfrankreich benannt.<a href="#_ftn15" name="_ftnref15">[15]</a> &Uuml;ber die Pariser Buchmalerei gelangte er im zisterziensischen Verbreitungsnetz auf die iberische Halbinsel sowie nach Italien und Deutschland.<a href="#_ftn16" name="_ftnref16">[16]</a> In der Zeit um beziehungsweise kurz nach 1200 erreichten indirekte Impulse dieses Stils &ndash; wie das Heiligenkreuzer und auch das Zwettler Legendar zeigen &ndash; den &ouml;sterreichischen Raum.</p>
    <p>Die in Cod. 14 t&auml;tige f&uuml;nfte Hand ist der stilistisch interessanteste Zeichner im Heiligenkreuzer Legendar, da er die Hauptstr&ouml;mungen der im Legendar wirksamen Einfl&uuml;sse auf sich vereint. Bei seinen Rankeninitialen zeigt er neben Spuren des Channel Style Einwirkungen der Manuskriptgruppe um den Heiligenkreuzer <a href="http://manuscripta.at/?ID=30389" target="_blank">Cod. 24</a>, die ihrerseits von der rheinl&auml;ndisch gepr&auml;gten Regensburg-Pr&uuml;feninger Buchmalerei beeinflusst wurde, und seine fig&uuml;rlichen Initialen reflektieren franz&ouml;sische Einfl&uuml;sse wie sie in Teilen der Heiligenkreuzer Sammelhandschrift Cod. 226 nachgewiesen werden k&ouml;nnen.</p>
    <p>&nbsp;</p>
    <p><strong>Zwettl &ndash; Gro&szlig;projekt und stilistischer Melting Pot II</strong></p>
    <p>Wie im Falle des Heiligenkreuzer Legendars best&auml;tigen sich f&uuml;r das Zwettler MLA im Gro&szlig;en und Ganzen die bisherigen Erkenntnisse zu Lokalisierung und Datierung: Dieses Werk wurde vor Ort im Zisterzienserstift Zwettl, das 1137/38 von dem Babenberger-Ministerialen Hadmar von Kuenring als Familiengrablege gegr&uuml;ndet und von Heiligenkreuz aus besiedelt worden war, im ersten Viertel des 13. Jahrhunderts (auf jeden Fall vor 1246) geschaffen.<a href="#_ftn17" name="_ftnref17">[17]</a> F&uuml;r Zwettl als Entstehungsort sprechen die lokalen Schreiber und Buchmaler (vgl. <a href="http://www.scriptoria.at/cgi-bin/sc_mss.php" target="_blank">scriptoria.at</a>).</p>
    <p>Die Liste der Salzburger Bisch&ouml;fe, die im Heiligenkreuzer Legendar (Cod. 14, <a href="http://manuscripta.at/diglit/AT3500-14/0066?sid=90bda636da41760be652079f6684ee0f" target="_blank">f. 32vb</a>) bis Adalbert III. reicht, endet im Zwettler MLA (Cod. 15, <a href="http://manuscripta.at/diglit/AT9800-15/0068" target="_blank">f. 33va</a>) mit Erzbischof Eberhard II. (1200&ndash;1246), der explizit als der gegenw&auml;rtige Amtsinhaber angesprochen wird (<em>&hellip; usque ad presentem dominum E</em>[<em>berhardum</em>]). Cod. 15 ist der letzte Band des Zwettler Legendars, der Schreibvorgang war zum Zeitpunkt des Listeneintrags also schon relativ weit gediehen. Daraus kann man folgern, dass das Zwettler Legendar zu Regierungs‑ beziehungsweise Lebzeiten Eberhards II., sprich ab beziehungsweise nach der Jahrhundertwende und somit im zeitlichen Anschluss an das Heiligenkreuzer Legendar entstanden ist. Als terminus ante quem der Entstehung des Zwettler MLA steht zweifelsohne das Todesjahr Eberhards II. (1246), die Arbeiten d&uuml;rften aber schon geraume Zeit davor abgeschlossen gewesen sein.</p>
    <p>F&uuml;r eine Datierung des Buchschmucks in das erste Viertel (oder eventuell Drittel) des 13. Jahrhunderts sprechen folgende Punkte: Die Haupthand des Zwettler Legendars (Hand 3), die in Cod. 24, 14 und 15 t&auml;tig war, wurde stilistisch durch das Antiphonar Heiligenkreuz, StiB, Cod. 20 beeinflusst, das sich durch die Darstellung des Heiligenkreuzer Abtes Werner (f. 168r), welcher sein Amt von 1203 bis 1227 aus&uuml;bte, in das erste Viertel des 13. Jahrhunderts datieren l&auml;sst. Die Einleitungsinitiale des zweiten Bandes (Cod. 24, <a href="http://manuscripta.at/diglit/AT9800-24/0006" target="_blank">f. 3va1</a>) legt von der im ersten Drittel des 13. Jahrhunderts in der Zisterze Baumgartenberg gepflegten Buchmalerei Zeugnis ab. Einer der zum Vergleich herangezogenen Baumgartenberger Codices (Linz, O&Ouml;LB, Cod. 480) enth&auml;lt einen Schenkungsvermerk, in dem unter anderem der Baumgartenberger Abt R&uuml;diger genannt wird, welcher sein Amt von 1207 bis 1232 aus&uuml;bte. Die Kreuzigungen in Cod. 14 (ff. 38vb, <a href="http://manuscripta.at/diglit/AT9800-14/0269" target="_blank">135rb</a>), die Christus jeweils mit ausgepr&auml;gtem K&ouml;rperschwung zeigen, entstanden an der Wende von der Romanik zur Gotik, wobei f. 135rb der bis ca. 1220 gebr&auml;uchliche Viernageltypus begegnet, was aber nicht als strikter terminus ante quem gewertet werden soll. Die erste Zwettler Hand wird neuerdings auf der Basis ikonographischer Untersuchungen in die 1220er Jahre datiert,<a href="#_ftn18" name="_ftnref18">[18]</a> was bedeuten w&uuml;rde, dass die Ausstattung des Zwettler Legendars nicht unmittelbar im Anschluss an die Fertigstellung des Heiligenkreuzer Legendars, sondern erst in den 1220er Jahren begonnen worden war und dann relativ schnell abgeschlossen wurde. Denn f&uuml;r eine nicht allzu sp&auml;te Datierung der Abschlussphase der Ausmalung spricht die vierte Zeichnerhand des Zwettler MLA, die stilistische Bez&uuml;ge zur ersten Heiligenkreuzer Hand und zum Rankenwerk der aufw&auml;ndigeren Initialmajuskeln des Zwettler Legendars aufweist.</p>
    <a href="/assets/Zwettl-Maler.pdf" target="_blank"><img style="max-width: 100%; max-height: 600px;" src="/img/zwettl_maler.png"></a>
    <p>Auch die Zwettler Legendensammlung darf als Gro&szlig;projekt bezeichnet werden und eignet sich wie das Heiligenkreuzer Legendar sehr gut, um Bearbeitungsstrategien zu veranschaulichen, die im Verlauf solch einer umfangreichen Ausstattung angewandt wurden. Es ist ebenfalls die lagenweise Aufteilung und Abarbeitung des Buchschmucks zu beobachten und als wichtiger Faktor des Arbeitsablaufs festzuhalten.</p>
    <p><strong>&nbsp;</strong></p>
    <p><strong>Verteilung des Buchschmucks im Zwettler Exemplar</strong></p>
    <p>Das Zwettler Legendar wurde gro&szlig;z&uuml;giger mit fig&uuml;rlichen Initialen bedacht als das Heiligenkreuzer, beinhaltet aber weitaus weniger Rankeninitialen. Seine knapp 1000 Folios wurden von vier H&auml;nden mit 148 fig&uuml;rlichen Initialen (Heiligenkreuz: 45) und 263 Rankeninitialen (Heiligenkreuz: &uuml;ber 500) sowie einer gro&szlig;en Anzahl von verzierten Initialmajuskeln dekoriert. Einige wenige Initialmajuskeln tragen Fleuronn&eacute;e, das aus der Entstehungszeit des Legendars stammt. Am Zwettler Legendar haben weniger Buchmaler mitgewirkt als am Heiligenkreuzer MLA (f&uuml;nf H&auml;nde, maximal zehn Einzelzeichner): Die vier Zwettler H&auml;nde d&uuml;rften sich in maximal sechs Einzelkr&auml;fte untergliedern lassen.</p>
    <p>W&auml;hrend sich im Heiligenkreuzer Legendar Beschleunigungstendenzen erst gegen Ende des Dekorationsprozesses bemerkbar machen, lassen sich derartige Bestrebungen im Zwettler Legendar bereits ab dem zweiten Band (Cod. 24) konstatieren, in dem man den leichter zu zeichnenden Rankeninitialen (110 St&uuml;ck) klar den Vorrang vor den komplizierteren fig&uuml;rlichen Initialen (39 St&uuml;ck) gab. Diese Ver&auml;nderung in der Ausstattungskonzeption wurde von einer neuen Zeichnerhand (Hand 3) eingebracht, die den zweiten Band zur G&auml;nze gestaltete. Besonders gut ist die Umgewichtung im letzten Drittel des Bandes zu erkennen, wo ein Mitarbeiter von Hand 3 t&auml;tig wurde. Auf ein enges zeitliches und r&auml;umliches Zusammenwirken der Kr&auml;fte deutet der Sachverhalt hin, dass in den Bereichen der ersten und dritten Hand singul&auml;re, von den anderen H&auml;nden geschaffene fig&uuml;rliche Initialen auftauchen.<a href="#_ftn19" name="_ftnref19">[19]</a></p>
    <p>Die dritte Hand kann als Hauptkraft der Zwettler Legendarsausstattung bezeichnet werden, da von ihr das Gros der Rankeninitialen und der fig&uuml;rlichen Initialen in Cod. 24, 14 und 15 stammt. Nachdem sie in Cod. 24 von einer Hilfskraft unterst&uuml;tzt worden war, schuf Hand 3 in Cod. 14 alle Rankeninitialen und fig&uuml;rlichen Initialen, in Cod. 15 die erste H&auml;lfte der Rankeninitialen und alle fig&uuml;rliche Initialen, die sich auf die ersten acht Lagen konzentrieren. Da Cod. 14 und 15 vormals eine Einheit bildeten, zeichnet diese Hand also f&uuml;r drei Viertel dieses &bdquo;Gro&szlig;bandes&ldquo; verantwortlich. In den Lagen 31 und 35 (entspricht Cod. 15, Lage 5 und 9) taucht ein weiterer Zeichner (Hand 4) auf, der dann das verbleibende Viertel von Cod. 14/15 mit Rankeninitialen ausstattete. Ab der neunten Lage sind in Cod. 15 keine fig&uuml;rlichen Initialen mehr eingezeichnet, doch die Zeilenh&ouml;he der Initialanlage spricht daf&uuml;r, dass man solche vorgesehen hatte. Die altert&uuml;mlichere und etwas plumpe vierte Hand besa&szlig; entweder nicht die zeichnerischen F&auml;higkeiten, um fig&uuml;rliche Initialen auszuf&uuml;hren, oder beschleunigte durch die Wahl des einfacheren Initialtyps bewusst den Ausstattungsprozess, der zu diesem Zeitpunkt dem Ende entgegen ging (vgl. Cod. 24).</p>
    <p>Wie beim Heiligenkreuzer Legendar fehlt ein Teil der Legenden &ndash; und zwar f&uuml;r den Zeitraum von Juli bis September. Die Kontinuit&auml;t im Buchschmuck von Cod. 24 zu 14/15 k&ouml;nnte daf&uuml;r sprechen, dass hier nicht, wie im Fall des Heiligenkreuzer MLA, ein Teil verloren gegangen, sondern gar nicht erst kopiert worden ist.<a href="#_ftn20" name="_ftnref20">[20]</a></p>
    <p><strong>&nbsp;</strong></p>
    <p><strong>Einfl&uuml;sse aus Heiligenkreuz</strong></p>
    <p>Stilistisch beeinflussend wirkte vor allem die Buchmalerei des Zwettler Mutterklosters Heiligenkreuz, insbesondere das gegen Ende des 12. Jahrhunderts (1183 bis um 1200) entstandene Heiligenkreuzer Legendar sowie das Antiphonar Cod. 20. Die Einfl&uuml;sse lassen sich haupts&auml;chlich bei den Zwettler H&auml;nden 2 und 3 festmachen. So zeigt Hand 2 sowohl bei den Draperien als auch im Rankenwerk Affinit&auml;ten zur Heiligenkreuzer Hand 5; zudem spiegeln sich in ihrer Figurengestaltung Regensburg-Pr&uuml;feninger Einwirkungen wider wie sie speziell auch bei der ersten Heiligenkreuzer Hand zu beobachten sind. F&uuml;r Hand 3, die Haupthand des Zwettler MLA, lassen sich bei der Gestaltung der Rankeninitialen und bei den zoomorphen Motiven deutliche Verbindungen zur dritten Heiligenkreuzer Hand herausarbeiten (vgl. Maler-Zwettl). Des Weiteren beweist auch die vor allem ab f. 58v im Heiligenkreuzer Cod. 20 t&auml;tige Hand in der Gestaltung der Buchstabenk&ouml;rper und des Rankenwerks sowie im Figurenaufbau starke Parallelen zur Zwettler Hand 3. Die aufw&auml;ndigeren Initialmajuskeln in Cod. 14/15 erinnern durch ihr Rankenwerk sehr an Hand 1 des Heiligenkreuzer MLA, die ihrerseits Bezug zur Regensburg-Pr&uuml;feninger Buchmalerei erkennen l&auml;sst, sowie an eine Gruppe von vier Handschriften, welche wohl im Umkreis des Heiligenkreuzer Legendars entstanden sind.</p>
    <p>Von einem weiteren stilistischen Einfluss legt die <a href="http://manuscripta.at/diglit/AT9800-24/0006" target="_blank">Einleitungsinitiale</a> des Cod. 24 Zeugnis ab. Sie weist Baumgartenberger Charakteristika auf, die im Legendar allerdings nur bei dieser einen Initiale begegnen. Der Zeichner der in Rede stehende Initiale war entweder intensiv mit der Baumgartenberger Buchmalerei vertraut oder stammte aus Baumgartenberg selbst. Baumgartenberg (1141) ist nach Zwettl (1138) die zweite Tochtergr&uuml;ndung, die von Heiligenkreuz aus erfolgte, so dass ein auf das Buchwesen bezogener Austausch zwischen den Tochterkl&ouml;stern beziehungsweise innerhalb des Zisterzendreiecks Heiligenkreuz-Zwettl-Baumgartenberg nicht verwundert.<a href="#_ftn21" name="_ftnref21">[21]</a> Auch in Baumgartenberg trug man um die Wende des 12. zum 13. Jahrhundert Heiligenviten zusammen (s. beispielsweise die Codices Linz, Ober&ouml;sterreichische Landesbibliothek, Cod. 422 und <a href="http://digi.landesbibliothek.at/viewer/resolver?urn=urn:nbn:at:AT-OOeLB-770109" target="_blank">473</a> sowie Wien, Schottenstift, <a href="http://manuscripta.at/?ID=28694" target="_blank">Cod. 189</a>) und pflegte diesbez&uuml;glich den Austausch mit Zwettl; so diente der Zwettler <a href="http://manuscripta.at/?ID=31660" target="_blank">Cod. 49</a> als Textvorlage f&uuml;r den Linzer Cod. 473. Ein &auml;hnlicher Sachverhalt, der in diesem Fall den engen Skriptoriumskontakt zwischen Zwettl und dem Mutterkloster Heiligenkreuz illustriert, liegt mit der Initiale f. 2r im Zwettler Cod. 163 vor. Diese Handschrift entstand Ende des 12. Jahrhunderts in Zwettl, was weitere an der Handschrift beteiligte Zwettler Zeichner belegen. Die Initiale auf f. 2r wurde jedoch von einer Hand geschaffen, die starke Verbindungen zum Heiligenkreuzer Cod. 24 und dessen Umkreis aufweist, man vergleiche zum Beispiel die in bewusste Zwettler Initiale mit Heiligenkreuz, Cod. 24, f. 14/10vb oder f. 33/29ra.</p>
    <p>&nbsp;</p>
    <p><strong>St. P&ouml;lten und Lilienfeld &ndash; ordens&uuml;bergreifendes Buchschmuck-Netzwerk</strong></p>
    <p>Der in Wien aufbewahrte MLA-Band stammt aus St. P&ouml;lten, was auf der Basis des Buchschmucks mit Sicherheit behauptet werden kann. Schon das Admonter Exemplar, das im Benediktinerkontext entstand, zeigt, dass das Magnum Legendarium Austriacum kein vorzugsweise mit dem Zisterzienserorden verkn&uuml;pftes Projekt war. St. P&ouml;lten, vor 840 als Benediktinerkloster gegr&uuml;ndet, wurde ca. 1083 als Eigenkloster der Passauer Bisch&ouml;fe mit Augustiner-Chorherren besetzt. In St. P&ouml;lten f&uuml;hrten die Babenberger bereits um 1150 einen kirchliche und weltliche Macht verkoppelnden Schachzug aus, den sie 1168/69 in Admont wiederholten: Herzog Heinrich II. Jasomirgott (reg. 1144&ndash;1177) erh&auml;lt vom Passauer Bischof Konrad I. von Babenberg (reg. 1148&ndash;1164), der 1164 als Konrad II. Erzbischof von Salzburg wird, das Vogtamt des Chorherrenstiftes St. P&ouml;lten als Lehen.<a href="#_ftn22" name="_ftnref22">[22]</a></p>
    <p>Stift Lilienfeld, das 1202 vom Babenberger Herzog Leopold VI. als Grablege gegr&uuml;ndet und 1206 von Heiligenkreuz aus besiedelt worden war, ist nach Heiligenkreuz und Zwettl die dritte Zisterze, in deren Bibliothek sich ein Magnum Legendarium erhalten hat. Wie die Zwettler B&auml;nde 14 und 15 haben wohl auch die Lilienfelder Codices 58 und 59 vormals eine Einheit gebildet.<a href="#_ftn23" name="_ftnref23">[23]</a> Da zum einen der Schreiber der Cod. 58&ndash;60<a href="#_ftn24" name="_ftnref24">[24]</a> auch in weiteren Lilienfelder Codices begegnet und demnach als in Lilienfeld t&auml;tig anzunehmen ist und zum anderen nachgetragene (?) Rankeninitialen in Cod. 59 Verbindungen zur Lilienfelder Buchmalerei (Cod. 52, zu dieser Hs. s. u.) beweisen, erscheint es plausibel, dass auch die zeichnerische Ausstattung der Codices 58 und 59 (Cod. 60 blieb ohne bedeutenden Dekor) dort erfolgte. Allerdings ist die Hand, die in Cod. 58 und 59 die allermeisten Rankeninitialen zeichnete, in keinem anderen erhaltenen Lilienfelder Codex nachweisbar.<a href="#_ftn25" name="_ftnref25">[25]</a> Vielmehr steht diese Hand, wie auch der L&ouml;wenanteil der Silhouetten‑ und Rankeninitialen im Wiener Codex, in engem Verh&auml;ltnis zu charakteristischem Formengut von Federzeichnungsinitialen, das auch im Stift St. Florian gepflegt wurde, weshalb der Wiener Codex und das Lilienfelder Legendar in der vorliegenden Einleitung in einem gemeinsamen Abschnitt zusammengefasst werden.</p>
    <p>St. Florian ist ebenfalls ein Augustiner-Chorherrenstift, das etwas fr&uuml;her (1071) als das nur etwa 100 km &ouml;stlich liegende St. P&ouml;ltener Stift gegr&uuml;ndet worden war; Stift Lilienfeld befindet sich wiederum nur ca. 25 km s&uuml;dlich von St. P&ouml;lten &ndash; diese Entfernungen standen einem Austausch also nicht entgegen. Allerdings ist es schwierig, eine chronologische Abfolge der gegenseitigen Beeinflussungen festzulegen; mit Sicherheit l&auml;sst sich bislang nur eine gewisse, im ersten Drittel des 13. Jahrhunderts festzumachende Gleichzeitigkeit der betreffenden Erzeugnisse in St. P&ouml;lten, Lilienfeld und St. Florian konstatieren. Dabei wird der Wiener Codex wegen seiner N&auml;he zu den fr&uuml;hen um 1200 anzusetzenden Werken eines f&uuml;r die St. P&ouml;ltener Augustiner-Chorherren t&auml;tigen Buchmalers an den Anfang des 13. Jahrhunderts datiert. Im Fall des Lilienfelder MLA liefern die Stiftsgr&uuml;ndung und ‑besiedlung die termini post quos 1202 beziehungsweise 1206. F&uuml;r den terminus ante quem ist der obengenannte Lilienfelder Cod. 52 mit dem &auml;ltesten ca. 1230 zu datierenden Lilienfelder Bibliotheksverzeichnis, in welchem das Legendar aufgef&uuml;hrt ist, von Bedeutung.<a href="#_ftn26" name="_ftnref26">[26]</a> Die Parallelen zwischen den Rankeninitialen in Cod. 52 und den fl&uuml;chtigen, eventuell nachgetragenen Initialen in Cod. 59 k&ouml;nnten darauf hindeuten, dass dieser Buchschmucknachtrag um 1230 erfolgte oder dass &ndash; falls man nicht von einem Nachtrag ausgehen will &ndash; der gesamte Rankeninitialendekor des Cod. 59, und damit auch des Cod. 58, im ersten Drittel des 13 Jahrhunderts entstand.</p>
    <p>Auf jeden Fall lohnt der in der vorliegenden Analyse herausgearbeitete ordens&uuml;bergreifende Zusammenhang in der Buchschmuckvermittlung des 12. und 13. Jahrhunderts innerhalb eines engmaschigen Netzes von ober‑ und nieder&ouml;sterreichischer Klosterskriptorien noch weitere Untersuchungen, wobei die oft vernachl&auml;ssigten Federzeichnungsinitialen ber&uuml;cksichtigt werden m&uuml;ssen.</p>
    <p>&nbsp;</p>
    <p><strong>Melk &ndash; MLA-Buchschmuck in Hoch‑ und Sp&auml;tmittelalter</strong></p>
    <p>In Melk, das 1089 vom Babenberger Markgraf Leopold II. von einem Kanonikerstift in ein Benediktinerkloster umgewandelt worden war, hat sich die einzige vollst&auml;ndige Fassung des Magnum Legendarium Austriacum erhalten. Der Buchschmuck dieses siebenb&auml;ndigen Legendars &ndash; sowohl des Cod. 388, der dem 13. Jahrhundert entstammend zum urspr&uuml;nglichen Melker MLA geh&ouml;rt, als auch der restlichen im 15. Jahrhundert entstandenen B&auml;nde (Cod. 546, 97, 492, 101, 16, 100) &ndash; wurde in Melk geschaffen, worauf die lokalen Schreiber und Buchmaler sowie die Einb&auml;nde verweisen. Cod. 388 (Viten vom 1. Januar bis 14. Februar) d&uuml;rfte wie der Heiligenkreuzer Cod. 14 Teil eines Gro&szlig;bandes sein, dessen andere H&auml;lfte fehlt.<a href="#_ftn27" name="_ftnref27">[27]</a></p>
    <p>Cod. 388 ist stilistisch in die erste H&auml;lfte des 13. Jahrhunderts zu geben. Die Schriftdatierung, die auf eine Entstehung nach 1230 deutet,<a href="#_ftn28" name="_ftnref28">[28]</a> erlaubt eine Eingrenzung der Buchschmuckentstehung auf das vierte oder f&uuml;nfte Jahrzehnt des 13. Jahrhunderts. Dies wird durch die wesentlichen Melker Vergleichscodices <a href="http://manuscripta.at/?ID=8995" target="_blank">383</a>, <a href="http://manuscripta.at/?ID=8994" target="_blank">382</a> und <a href="http://manuscripta.at/?ID=8975" target="_blank">295</a> gest&uuml;tzt, eine Handschriftengruppe, die ebenfalls um 1230 geschrieben wurde.<a href="#_ftn29" name="_ftnref29">[29]</a></p>
    <p>Zum Zwettler Cod. 13 bestehen zwar eindeutige ikonographische Bez&uuml;ge, aber nur zu den beiden ersten fig&uuml;rlichen Initialen.<a href="#_ftn30" name="_ftnref30">[30]</a> Hierf&uuml;r muss wohl ein indirekter Vermittlungsweg angenommen werden, denn dar&uuml;ber hinaus lassen sich keine direkten inhaltlichen und stilistischen Verbindungen zwischen dem Zwettler MLA und Cod. 388 nachweisen. Vielmehr sprechen nicht nur die einfachen Fleuronn&eacute;e-Formen, sondern auch die sorgf&auml;ltigen Federzeichnungsinitialen ff. <a href="http://manuscripta.at/diglit/AT6000-388/0466" target="_blank">231v</a> und <a href="http://manuscripta.at/diglit/AT6000-388/0467" target="_blank">232r</a> f&uuml;r eine stilistische Verankerung des Cod. 388 im Melker Skriptorium.</p>
    <p>F&uuml;nf der sechs j&uuml;ngeren B&auml;nde wurden vornehmlich durch den von 1453 bis 1474 in Melk nachweisbaren Schreiber Christophorus Lieb(ner) kopiert, der sich im vorletzten Band namentlich nennt (<a href="http://manuscripta.at/diglit/AT6000-16/0684" target="_blank">Cod. 16, f. 343va</a>).<a href="#_ftn31" name="_ftnref31">[31]</a> Ebendort sowie f. <a href="http://manuscripta.at/diglit/AT6000-16/0693" target="_blank">348rb</a> trug Lieb die Datierung 1471 ein. Sollten die Melker MLA-B&auml;nde des 15. Jahrhunderts in kalendarischer Abfolge kopiert worden sein, dann bedeutet das, dass der Schreibvorgang schon vor 1470 (wohl zweite H&auml;lfte der 1460er Jahre) begonnen worden war und sich 1471 schon im fortgeschrittenen Stadium befand. Cod. 546 (Viten 1. bis. 31. Dezember), der sich in Format, Layout, Beschreibstoff, Ausstattung und Einband von den anderen Melker MLA-Handschriften des 15. Jahrhunderts abhebt, entstand wahrscheinlich vor Christopherus Liebs Schreibt&auml;tigkeit.</p>
    <p>Die Ergebnisse der Buchschmuck-Analyse der j&uuml;ngeren Melker MLA-B&auml;nde passen zum einen sehr gut zu diesem Entstehungsbild und legen dar&uuml;ber hinaus Zeugnis &uuml;ber die koh&auml;rente Weitervermittlung von Buchzier (und ihrer Vorlagen) im Melker Skriptorium des 15. Jahrhunderts ab. Ein entscheidender Impuls f&uuml;r den Deckfarbenschmuck ging aus von der nicht nur f&uuml;r die Melker, sondern vor allem f&uuml;r die Wiener Buchmalerei der ersten H&auml;lfte des 15. Jahrhunderts bedeutsamen Illuminatorenpers&ouml;nlichkeit des Albrechtsminiators und spiegelt sich, vermittelt durch eine umf&auml;ngliche Gruppe von Melker Handschriften aus dem dritten Jahrhundertviertel (mit Schwerpunkt in den 1450er Jahren), in den meisten j&uuml;ngeren MLA-Handschriften wider. Immer vorausgesetzt, dass das Kopieren kalendarisch und das Ausschm&uuml;cken sukzessiv erfolgte, ergibt sich folgende Chronologie der j&uuml;ngeren Melker MLA-B&auml;nde (zu Cod. 546, der ohne nennenswerten Buchschmuck belassen wurde, s. o.): Cod. 97, 492 und 101 entstanden vor 1471. Die Vergleiche f&uuml;r den fleuronnierten Cod. 492 deuten auf eine Ausschm&uuml;ckung in den 1460er Jahren. Cod. 97 und 101 stehen im Kontext der vom Albrechtsminiator inspirierten Codexgruppe, so dass sie ins dritte Viertel des 15. Jahrhunderts zu geben sind, auf jeden Fall vor 1471. Dem 1471 datierten Cod. 16 kann eine Vergleichshandschrift von 1474 (Cod. 132) zugeordnet werden, so dass sich eine Datierung nach 1471 bis um die Mitte der 1470er Jahre plausibel argumentieren l&auml;sst. Cod. 100 kann aufgrund seiner 1486 datierten Vergleichshandschrift (Cod. 99) ohne Weiteres in die 1470er Jahre (mit Tendenz zum Ende des Jahrzehnts) gegeben werden.</p>
    <p>&nbsp;</p>
    <hr></hr>
    <p><a href="#_ftnref1" name="_ftn1">[1]</a> Diese Untersuchung wurde im Rahmen des FWF-Spezialforschungsbereiches (SFB) &bdquo;Visions of Community (VISCOM): Comparative Approaches to Ethnicity, Region and Empire in Christianity, Islam and Buddhism (400-1600 CE)&ldquo; (Leitung: Walter Pohl, &Ouml;AW, Wien) im Teilprojekt &bdquo;Social and Cultural Communities across Medieval Monastic, Civic, and Courtly Cultures in High and Late Medieval Central Europe&ldquo; (Leitung: Christina Lutter, Universit&auml;t Wien) durchgef&uuml;hrt. &ndash; Die eingeflossenen Buchschmuckvergleiche w&auml;ren ohne den Zugang zum umfangreichen Bildfundus der Bibliotheksstiftung Otto P&auml;cht, Wien, nicht zu leisten gewesen. &ndash; F&uuml;r all ihre wertvollen Hinweise und Hilfestellungen danke ich sehr herzlich meinen Kolleginnen und Kollegen Christine Gla&szlig;ner (&Ouml;AW Wien), Martin Haltrich (Stiftsbibliothek Klosterneuburg), Katharina Hranitzky (Universit&auml;t Wien), Martin Roland (&Ouml;AW Wien), Lena Sommer (Universit&auml;t Hamburg). Zu besonderem Dank bin ich Michaela Schuller-Juckes (Universit&auml;t Wien) verpflichtet, die den Text Korrektur gelesen hat.</p>
    <p><a href="#_ftnref2" name="_ftn2">[2]</a> Das Heiligenkreuzer Fragment HS 7F/8, das codicologisch hochinteressant ist, wurde in der Analyse nicht explizit ber&uuml;cksichtigt, da es zwar die &Uuml;berarbeitungsmarken des Heiligenkreuzer M&ouml;nchs Ambrosius (um 1300) tr&auml;gt, jedoch keinen bedeutenderen Buchschmuck</p>
    <p><a href="#_ftnref3" name="_ftn3">[3]</a> Siehe Augustyn 2007, speziell 64.</p>
    <p><a href="#_ftnref4" name="_ftn4">[4]</a> Klemm 1987, 42f.</p>
    <p><a href="#_ftnref5" name="_ftn5">[5]</a> Siehe, auch f&uuml;r die nachfolgenden Ausf&uuml;hrungen, &Oacute; Riain 2015, insbes. 138f.</p>
    <p><a href="#_ftnref6" name="_ftn6">[6]</a> &Oacute; Riain 2015, 136f.</p>
    <p><a href="#_ftnref7" name="_ftn7">[7]</a> &Oacute; Riain 2015, 101 mit Anm. 44.</p>
    <p><a href="#_ftnref8" name="_ftn8">[8]</a> Simader, Admont 2007, 362f.</p>
    <p><a href="#_ftnref9" name="_ftn9">[9]</a> Vgl. Simader, Heiligenkreuz 2007, 356; Fingernagel 1985/2, 63f., &Oacute; Riain 2015, 135f. sowie manuscripta.at.</p>
    <p><a href="#_ftnref10" name="_ftn10">[10]</a> Da Otto von Bamberg in seiner Vita als &bdquo;sanctus&ldquo; bezeichnet wird (Cod. 12, f. 308r) &ndash; seine Heiligsprechung erfolgte 1189 &ndash;, wird in der Literatur auch dieses Jahr als terminus post quem herangezogen; Diarmuid &Oacute; Riain h&auml;lt diese Annahme f&uuml;r problematisch (Diskussion s. &Oacute; Riain 2015, 136f.).</p>
    <p><a href="#_ftnref11" name="_ftn11">[11]</a> Pr&uuml;fening wurde 1109 von Bischof Otto von Bamberg gegr&uuml;ndet und 1114 mit M&ouml;nchen aus dem Reformkloster Hirsau im Schwarzwald besiedelt, woraus sich in Bezug auf die Pr&uuml;feninger Handschriftenproduktion in ihren Anf&auml;ngen zum einen Relationen zur schw&auml;bischen Buchmalerei ergeben, zum anderen l&auml;sst sich eine Einflussnahme der &auml;lteren bayerischen Tradition konstatieren und schlie&szlig;lich &ndash; sowohl f&uuml;r die fig&uuml;rlichen als auch f&uuml;r die Rankeninitialen &ndash; der bereits angef&uuml;hrte Einfluss der rheinischen Buchmalerei (s. Klemm 1987, 43f.).</p>
    <p><a href="#_ftnref12" name="_ftn12">[12]</a> Fingernagel 1985/2, u. a. 207f.; Klemm 1987, 41, 44; Wolter-von dem Knesebeck 2007, 249&ndash;251; Simader, Heiligenkreuz 2007, 356; Klemm 2012, 260.</p>
    <p><a href="#_ftnref13" name="_ftn13">[13]</a> Zu Kuno von Siegburg bzw. Regensburg, auch Konrad I. von Raitenbuch s. Lorenz Weinrich, Lorenz, &bdquo;Konrad I.&ldquo;, in: Neue Deutsche Biographie 12 (1979) 523; auch unter der URL: http://www.deutsche-biographie.de/pnd122224817.html (letzter Zugriff: 09.06.2016).</p>
    <p><a href="#_ftnref14" name="_ftn14">[14]</a> Siehe insbes. Fingernagel 1985/2, 197f. und Simader, Heiligenkreuz 2007, 356.</p>
    <p><a href="#_ftnref15" name="_ftn15">[15]</a> Zum Channel Style u. a. Christine Jakobi-Mirwald, Das mittelalterliche Buch. Funktion und Ausstattung. Stuttgart 2004, 255 und Nilgen 2007, 159&ndash;161.</p>
    <p><a href="#_ftnref16" name="_ftn16">[16]</a> Siehe Augustyn 2007, 67.</p>
    <p><a href="#_ftnref17" name="_ftn17">[17]</a> Vgl. Simader, Zwettl 2007, 360; Fingernagel 1985/2, 67f. sowie manuscripta.at.</p>
    <p><a href="#_ftnref18" name="_ftn18">[18]</a> Sommer (in Vorbereitung).</p>
    <p><a href="#_ftnref19" name="_ftn19">[19]</a> So befindet sich die Paulus-Initiale Cod. 13, f. 73ra, die von Hand 3 stammt, im Bereich von Hand 1 (Cod. 13, ff. ff. 2va&ndash;82vb) und die von Hand 2 ausgef&uuml;hrte Origenes-Initiale Cod. 24, f. 183ra, im Bereich von Hand 3 (ff. 15vb&ndash;286va).</p>
    <p><a href="#_ftnref20" name="_ftn20">[20]</a> Siehe &Oacute; Riain 2015, 107.</p>
    <p><a href="#_ftnref21" name="_ftn21">[21]</a> Die Kl&ouml;ster liegen nicht mehr als 140 km voneinander entfernt: Heiligenkreuz-Zwettl 125 km, Heiligenkreuz-Baumgartenberg 135 km, Zwettl-Baumgartenberg knapp 80 km.</p>
    <p><a href="#_ftnref22" name="_ftn22">[22]</a> Vgl. &Oacute; Riain 2015, 104.</p>
    <p><a href="#_ftnref23" name="_ftn23">[23]</a> Siehe &Oacute; Riain 2015, 107.</p>
    <p><a href="#_ftnref24" name="_ftn24">[24]</a> Zum Schreiber des Lilienfelder <a href="http://www.scriptoria.at/cgi-bin/scribes.php?ms=AT5400-60" target="_blank">Cod. 60 s.</a> unter Cod. 34: Hand A, die in Lilienfeld im ersten Drittel des 13. Jahrhunderts t&auml;tig war und sich au&szlig;er in Cod. 60 in folgenden Lilienfelder Codices nachweisen l&auml;sst: 34, 52, 54, 101, 108, 131, 140, 168, 181, 185 und 189 sowie, um 1200, in den beiden Heiligenkreuzer Codices 90 und 123 (Heiligenkreuz als Schreib‑ und Aufbewahrungsort).</p>
    <p><a href="#_ftnref25" name="_ftn25">[25]</a> Zur Handgleichheit in Bezug auf die Rankeninitialen s. Roland 1996, 18, 22f. (Kat. 1/3 und 1/4). Die hier vorgeschlagene Handgleichheit mit dem Lilienfelder Cod. 163 ist allerdings nicht nachvollziehbar.</p>
    <p><a href="#_ftnref26" name="_ftn26">[26]</a> Fol. f. 247v: <em>II passionalia</em>; zur Datierung Haidinger/Lackner 1997, 63; &Oacute; Riain 2015, 108 (Anm. 67) weist darauf hin, dass der betreffende Eintrag, der am Ende des Verzeichnisses steht, von einer etwas sp&auml;teren Hand stammt.</p>
    <p><a href="#_ftnref27" name="_ftn27">[27]</a> Siehe &Oacute; Riain 2015, 107.</p>
    <p><a href="#_ftnref28" name="_ftn28">[28]</a> Ebd., 137 mit Verweis auf Haidinger 1989, 45, Anm. 129.</p>
    <p><a href="#_ftnref29" name="_ftn29">[29]</a> Siehe Schmidt 1963/2005, 97 bzw. 14, Nr. 2.</p>
    <p><a href="#_ftnref30" name="_ftn30">[30]</a> Zwettl, Cod. 13, f. 2va und Melk, Cod. 388, f. 1r (Hieronymus, Chromatius und Heliodor) sowie Zwettil Cod. 13, f. 3ra und Melk, Cod. 388, f. 2v (Basilius und Eubulus).</p>
    <p><a href="#_ftnref31" name="_ftn31">[31]</a> Zu diesem aus Isny stammenden Schreiber s. Kr&auml;mer, Scriptores sowie Meta Niederkorn-Bruck, Profe&szlig;buch des Klosters Melk. 1. Teil. 1418&ndash;1452 (Stift Melk. Geschichte und Gegenwart 4). St. P&ouml;lten 1985, 79&ndash;202, hier 182f.</p>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        data() {
            return {
            }
        },
        mounted() {
        },
        methods: {
        }
    }
</script>

<style lang="scss">

</style>
