name: Create image and Deploy

env:
  image_tagged: mla:latest
  default_port: 5000
  source_image: tmp-cnb-image

on:
  push:
    branches:
      - 'master'

jobs:
  build_and_push_to_registry:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pack Build
        uses: dfreilich/pack-action@v2.0.0
        with:
          args: 'build tmp-cnb-image --builder heroku/buildpacks:20'
      - name: create Dockerfile
        run: |
          cat >> Dockerfile <<END  
          ARG source_image
          FROM ${source_image}
          ARG default_port
          ENV PORT=${default_port}
          EXPOSE ${default_port}
          END

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} \
            .        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: source_image=tmp-cnb-image,default_port=5000
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            acdhch/${{ env.image_tagged }}
            ghcr.io/acdh-oeaw/${{ env.image_tagged }}
  rancher:
    needs: build_and_push_to_registry
    name: Deploy to rancher
    runs-on: ubuntu-20.04
    steps:
    - name: Rancher Deploy Action
      run: |
        curl -i -X POST "${{ secrets.RANCHERURL }}?action=redeploy" -H "Authorization: Bearer ${{ secrets.RANCHER_BARER_TOKEN }}"
