name: Create image and Deploy

env:
  IMAGE_TAG: mla:latest
on:
  push:
    branches:
      - 'master'
jobs:
  build_and_push_to_registry:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
# As of May 2022 CNB does not create multi-arch builds
# and we cannot use them on our amd64 hardware
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   
      - name: Pack Build
        uses: dfreilich/pack-action@v2.1.1
        with:
          args: 'build tmp-cnb-image --builder heroku/buildpacks:18'
      - name: Suggest default port 5000 within image
        run: |
          cat >> Dockerfile <<EOF  
          FROM tmp-cnb-image
          ENV PORT=5000
          EXPOSE 5000          
          EOF
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            acdhch/${{ env.IMAGE_TAG }}
            ghcr.io/acdh-oeaw/${{ env.IMAGE_TAG }}
  rancher:
    needs: build_and_push_to_registry
    name: Deploy to rancher
    runs-on: ubuntu-20.04
    steps:
    - name: Rancher Deploy Action
      run: |
        curl -i -X POST "${{ secrets.RANCHERURL }}?action=redeploy" -H "Authorization: Bearer ${{ secrets.RANCHER_BARER_TOKEN }}"
