name: Create image and Deploy

env:
  IMAGE_TAG: mla:latest

on:
  push:
    branches:
      - 'master'

jobs:
  build_and_push_to_registry:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: generate build instructions using herokuish
        run: |
          cat >> Dockerfile <<END   
          FROM heroku/buildpacks:18 as builder
          COPY . /tmp/app
          ENV USER=heroku
          RUN /bin/heroku buildpack build
          
          FROM heroku/buildpacks:18
          COPY --chown=heroku:heroku --from=builder /app /app
          ENV PORT=5000
          ENV USER=heroku
          EXPOSE 5000
          CMD ["/bin/heroku", "procfile", "start", "web"]

          # END  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            acdhch/${{ env.IMAGE_TAG }}
            ghcr.io/acdh-oeaw/${{ env.IMAGE_TAG }}
  rancher:
    needs: build_and_push_to_registry
    name: Deploy to rancher
    runs-on: ubuntu-20.04
    steps:
    - name: Rancher Deploy Action
      run: |
        curl -i -X POST "${{ secrets.RANCHERURL }}?action=redeploy" -H "Authorization: Bearer ${{ secrets.RANCHER_BARER_TOKEN }}"